name: advancementRanking
version: '0.0.0'
main: fox.ryukkun_.advancementRanking.Main
api-version: '1.21'
commands:
  advancement-ranking:
    description: 進捗の達成率のランキングについて教えてくれるよ！
    usage: advancement-ranking min<int> max<int>
    permission: advancement-ranking.board
  advancement-progress:
    description: 個々の進捗の達成率について
    usage: advancement-progress target<Player>
    permission: advancement-ranking.progress


permissions:
  advancement-ranking.board:
    default: op
  advancement-ranking.progress:
    default: true