name: advancementRanking
version: '0.0.0'
main: fox.ryukkun_.advancementRanking.Main
api-version: '1.21'
commands:
  advancement-ranking:
    description: 進捗の達成率について教えてくれるよ！
    usage: advancement-ranking min<int> max<int>
    permission:

permissions:
  advancementranking.commands:
    default: op
